# Generated by Django 4.0 on 2021-12-28 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_delete_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85dd606e-21af-4a0a-bd32-1b3cec06da71'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
