# Generated by Django 4.0 on 2021-12-28 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d81ae9f-93ca-4fea-a956-21c4c0c7fc23'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
